### ISSUE TITLE
loadConfigData.size() is sometimes larger than sizeof(loadConfig)

### ISSUE THREAD

**Issue by haxmeadroom** [trailofbits/winchecksec#41]
https://github.com/trailofbits/winchecksec/blob/master/Checksec.cc#L88
```c
    peparse::image_load_config_32 loadConfig;
    memcpy_s(&loadConfig, sizeof(loadConfig), loadConfigData.data(),
             loadConfigData.size());
```

To repro, run winchecksec on itself:
```
PS Z:\winchecksec\win> .\Debug\winchecksec.exe .\Debug\winchecksec.exe
PS Z:\winchecksec\win>
```
You'll get no output, because the `memcpy_s` fails. Is this peparses fault or the use of it?

**Comment by woodruffw** [comment]
Looking into this.

**Comment by haxmeadroom** [comment]
Affects linux version (which has the extra check and error message)
```
$ ./winchecksec  ../../exes/winchecksec.exe 
Error: loadConfigData is bigger than loadConfig.
Syntax : ./winchecksec [-j] <dll|exe>
Example: ./winchecksec -j doom2.exe
  -j will output json to stdout 
```

**Comment by woodruffw** [comment]
Alright, was able to confirm with VC 2019 x64. The VC 2019 Win32 build doesn't error, which makes me suspect that this is a sizing or layout issue with the different load data structures. Continuing to dig.

**Comment by woodruffw** [comment]
Yeah, it looks like VC 2019's linker adds some new (currently undocumented) fields to the load config. These fields seem to be PE32+ only, since the PE32 load config consistently returns with the expected size on both VC 2017 and 2019. Truncating the load config should be safe since it's what the public definitions encourage, so I'll do that.
